/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  plugins: [],
  theme: {
    extend: {
      fontFamily: {
        sansserif: ['sans-serif'],
      },
      colors: {
        'purple-100': '#F2EEF5',
        'purple-200': '#F8EFFF',
        'purple-300': '#EFDBFF',
        'purple-400': '#A68BBC',
        'purple-800': '#3D2351',
        'purple-900': '#2A113E',
        'fushia-100': '#FEDFFE',
        'fushia-200': '#FCBFFD',
        'fushia-300': '#F987FC',
        'fushia-400': '#F85FFB',
        'fushia-500': '#D52AD9',
      },
      fontSize: {
        'heading-1': ['44px', { lineHeight: '50px' }],
        'heading-2': ['32px', { lineHeight: '40px' }],
        'heading-3': ['24px', { lineHeight: '30px' }],
        'heading-4': ['20px', { lineHeight: '24px' }],
        'heading-5': ['16px', { lineHeight: '20px' }],
        'heading-lg': ['60px', { lineHeight: '70px' }],
        'heading-xl': ['80px', { lineHeight: '90px' }],
        'heading-xxl': ['90px', { lineHeight: '100px' }],
        sm: ['12px', { lineHeight: '16px' }],
        md: ['14px', { lineHeight: '22px' }],
        lg: ['16px', { lineHeight: '24px' }],
        xl: ['40px', { lineHeight: '60px' }],
      },
      screens: {
        '2xs': '375px',
        xs: '768px',
        sm: '1024px',
        md: '1280px',
        lg: '1440px',
        xl: '1920px',
        '2xl': '2560px',
      },
      spacing: {
        '3xs': '2px',
        '2xs': '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '20px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '40px',
        '4xl': '48px',
        '5xl': '56px',
        '6xl': '64px',
        '7xl': '72px',
        '8xl': '80px',
      },
    },
  },
}
